



CREATE USER TIQUICIATECH IDENTIFIED BY "123456789Proyecto";

GRANT CREATE SESSION TO TIQUICIATECH;
grant create TABLE, create VIEW,create SEQUENCE, create procedure,create TRIGGER,
create synonym to TIQUICIATECH;
GRANT RESOURCE TO TIQUICIATECH;


ALTER USER TIQUICIATECH QUOTA UNLIMITED ON DATA;

GRANT EXECUTE ON SYS.DBMS_STATS TO TIQUICIATECH;