

-- =====================================================
-- LIMPIEZA 
-- =====================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MOVIMIENTO_DETALLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MOVIMIENTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVENTARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROVEEDOR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================================================
-- TABLAS BASE
-- =====================================================

CREATE TABLE ROL (
    id_rol          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE CATEGORIA (
    id_categoria    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(80) NOT NULL,
    descripcion     VARCHAR2(255),
    estado          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre),
    CONSTRAINT ck_categoria_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE PROVEEDOR (
    id_proveedor    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(120) NOT NULL,
    telefono        VARCHAR2(30),
    email           VARCHAR2(120),
    direccion       VARCHAR2(255),
    estado          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT uq_proveedor_email UNIQUE (email),
    CONSTRAINT ck_proveedor_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- =====================================================
-- TABLAS DEPENDIENTES
-- =====================================================

CREATE TABLE USUARIO (
    id_usuario          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol              NUMBER NOT NULL,
    nombre              VARCHAR2(120) NOT NULL,
    email               VARCHAR2(120) NOT NULL,
    password_hash       VARCHAR2(255) NOT NULL,
    estado              VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
        REFERENCES ROL(id_rol),
    CONSTRAINT ck_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE PRODUCTO (
    id_producto         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria        NUMBER NOT NULL,
    id_proveedor        NUMBER NOT NULL,
    sku                 VARCHAR2(50) NOT NULL,
    nombre              VARCHAR2(120) NOT NULL,
    descripcion         VARCHAR2(255),
    precio              NUMBER(10,2) NOT NULL,
    estado              VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_producto_sku UNIQUE (sku),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria)
        REFERENCES CATEGORIA(id_categoria),
    CONSTRAINT fk_producto_proveedor FOREIGN KEY (id_proveedor)
        REFERENCES PROVEEDOR(id_proveedor),
    CONSTRAINT ck_producto_precio CHECK (precio >= 0),
    CONSTRAINT ck_producto_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE INVENTARIO (
    id_inventario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto         NUMBER NOT NULL,
    stock_actual        NUMBER NOT NULL,
    stock_minimo        NUMBER NOT NULL,
    stock_maximo        NUMBER,
    CONSTRAINT uq_inventario_producto UNIQUE (id_producto),
    CONSTRAINT fk_inventario_producto FOREIGN KEY (id_producto)
        REFERENCES PRODUCTO(id_producto),
    CONSTRAINT ck_stock_actual CHECK (stock_actual >= 0),
    CONSTRAINT ck_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_stock_maximo CHECK (stock_maximo IS NULL OR stock_maximo >= stock_minimo)
);

CREATE TABLE MOVIMIENTO (
    id_movimiento       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          NUMBER NOT NULL,
    tipo                VARCHAR2(20) NOT NULL,
    fecha               DATE DEFAULT SYSDATE NOT NULL,
    observacion         VARCHAR2(255),
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (id_usuario)
        REFERENCES USUARIO(id_usuario),
    CONSTRAINT ck_movimiento_tipo CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE'))
);

CREATE TABLE MOVIMIENTO_DETALLE (
    id_detalle          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_movimiento       NUMBER NOT NULL,
    id_producto         NUMBER NOT NULL,
    cantidad            NUMBER NOT NULL,
    costo_unitario      NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detalle_movimiento FOREIGN KEY (id_movimiento)
        REFERENCES MOVIMIENTO(id_movimiento),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto)
        REFERENCES PRODUCTO(id_producto),
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_costo CHECK (costo_unitario >= 0)
);



-- TESTING 

SELECT table_name
FROM user_tables
ORDER BY table_name;

-- METIENDO DATOS MINIMOS DE PRUEBA 

INSERT INTO ROL (nombre) VALUES ('ADMIN');
INSERT INTO ROL (nombre) VALUES ('OPERADOR');

INSERT INTO CATEGORIA (nombre, descripcion, estado)
VALUES ('Laptops', 'Equipos portátiles', 'ACTIVO');

INSERT INTO PROVEEDOR (nombre, telefono, email, direccion, estado)
VALUES ('TechSupplier CR', '8888-8888', 'proveedor@tech.com', 'San Jose', 'ACTIVO');

INSERT INTO USUARIO (id_rol, nombre, email, password_hash, estado)
VALUES (1, 'Joshua', 'joshua@tiquicia.com', '123456', 'ACTIVO');

COMMIT;


-- PROBANDO RELACIONES: 

INSERT INTO PRODUCTO (id_categoria, id_proveedor, sku, nombre, descripcion, precio, estado)
VALUES (1, 1, 'LAP-001', 'Laptop Asus', 'Laptop de prueba', 450000, 'ACTIVO');

INSERT INTO INVENTARIO (id_producto, stock_actual, stock_minimo, stock_maximo)
VALUES (1, 10, 2, 20);

COMMIT;




----- Procedimientos almacenados
--- CATEGORIA CRUD
-- INSERTAR
CREATE OR REPLACE PROCEDURE sp_insertar_categoria (
    p_nombre        IN CATEGORIA.NOMBRE%TYPE,
    p_descripcion   IN CATEGORIA.DESCRIPCION%TYPE,
    p_estado        IN CATEGORIA.ESTADO%TYPE
)
AS
BEGIN
    INSERT INTO CATEGORIA (nombre, descripcion, estado)
    VALUES (p_nombre, p_descripcion, p_estado);
END;
/
-- LISTAR
CREATE OR REPLACE PROCEDURE sp_listar_categorias (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_categoria, nombre, descripcion, estado
        FROM CATEGORIA
        ORDER BY id_categoria;
END;
/

-- ACTUALIZAR 

CREATE OR REPLACE PROCEDURE sp_actualizar_categoria (
    p_id_categoria  IN CATEGORIA.ID_CATEGORIA%TYPE,
    p_nombre        IN CATEGORIA.NOMBRE%TYPE,
    p_descripcion   IN CATEGORIA.DESCRIPCION%TYPE,
    p_estado        IN CATEGORIA.ESTADO%TYPE
)
AS
BEGIN
    UPDATE CATEGORIA
       SET nombre = p_nombre,
           descripcion = p_descripcion,
           estado = p_estado
     WHERE id_categoria = p_id_categoria;
END;
/

-- ELIMINAR 

CREATE OR REPLACE PROCEDURE sp_eliminar_categoria (
    p_id_categoria IN CATEGORIA.ID_CATEGORIA%TYPE
)
AS
BEGIN
    DELETE FROM CATEGORIA
    WHERE id_categoria = p_id_categoria;
END;
/

-- PRUEBAS RAPIDAS 

BEGIN
    sp_insertar_categoria('Monitores', 'Pantallas y monitores', 'ACTIVO');
    COMMIT;
END;
/

----------------------------------------------------
BEGIN
    sp_actualizar_categoria(1, 'Laptops y Portátiles', 'Equipos portátiles actualizados', 'ACTIVO');
    COMMIT;
END;
/

----------------------------------------------------
BEGIN
    sp_eliminar_categoria(2);
    COMMIT;
END;
/
----------------------------------------------------
VARIABLE rc REFCURSOR;

BEGIN
    sp_listar_categorias(:rc);
END;
/

PRINT rc;


-- PRUEBA DESPUES DE INSERT EN JAVA 
SELECT * FROM CATEGORIA; 
SELECT id_categoria, nombre, descripcion, estado
FROM CATEGORIA
ORDER BY id_categoria;





-- PROVEEDOR CRUD 
CREATE OR REPLACE PROCEDURE sp_insertar_proveedor (
    p_nombre      IN PROVEEDOR.NOMBRE%TYPE,
    p_telefono    IN PROVEEDOR.TELEFONO%TYPE,
    p_email       IN PROVEEDOR.EMAIL%TYPE,
    p_direccion   IN PROVEEDOR.DIRECCION%TYPE,
    p_estado      IN PROVEEDOR.ESTADO%TYPE
)
AS
BEGIN
    INSERT INTO PROVEEDOR (nombre, telefono, email, direccion, estado)
    VALUES (p_nombre, p_telefono, p_email, p_direccion, p_estado);
END;
/
--------------------------------------
CREATE OR REPLACE PROCEDURE sp_listar_proveedores (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_proveedor, nombre, telefono, email, direccion, estado
        FROM PROVEEDOR
        ORDER BY id_proveedor;
END;
/
--------------------------------------
CREATE OR REPLACE PROCEDURE sp_actualizar_proveedor (
    p_id_proveedor IN PROVEEDOR.ID_PROVEEDOR%TYPE,
    p_nombre       IN PROVEEDOR.NOMBRE%TYPE,
    p_telefono     IN PROVEEDOR.TELEFONO%TYPE,
    p_email        IN PROVEEDOR.EMAIL%TYPE,
    p_direccion    IN PROVEEDOR.DIRECCION%TYPE,
    p_estado       IN PROVEEDOR.ESTADO%TYPE
)
AS
BEGIN
    UPDATE PROVEEDOR
       SET nombre = p_nombre,
           telefono = p_telefono,
           email = p_email,
           direccion = p_direccion,
           estado = p_estado
     WHERE id_proveedor = p_id_proveedor;
END;
/
----------------------------------------
CREATE OR REPLACE PROCEDURE sp_eliminar_proveedor (
    p_id_proveedor IN PROVEEDOR.ID_PROVEEDOR%TYPE
)
AS
BEGIN
    DELETE FROM PROVEEDOR
    WHERE id_proveedor = p_id_proveedor;
END;
/

----PRUEBAS:
BEGIN
    sp_insertar_proveedor(
        'Distribuidora Tech CR',
        '8888-7777',
        'contacto@techcr.com',
        'San Jose, Costa Rica',
        'ACTIVO'
    );
    COMMIT;
END;
/

-- CURSOSR PROVEEDOR 
VARIABLE rc REFCURSOR;

BEGIN
    sp_listar_proveedores(:rc);
END;
/

PRINT rc;



--------------------------------------------------
--- PRODUCTO CRUD 
CREATE OR REPLACE PROCEDURE sp_insertar_producto (
    p_id_categoria    IN PRODUCTO.ID_CATEGORIA%TYPE,
    p_id_proveedor    IN PRODUCTO.ID_PROVEEDOR%TYPE,
    p_sku             IN PRODUCTO.SKU%TYPE,
    p_nombre          IN PRODUCTO.NOMBRE%TYPE,
    p_descripcion     IN PRODUCTO.DESCRIPCION%TYPE,
    p_precio          IN PRODUCTO.PRECIO%TYPE,
    p_estado          IN PRODUCTO.ESTADO%TYPE
)
AS
BEGIN
    INSERT INTO PRODUCTO (
        id_categoria,
        id_proveedor,
        sku,
        nombre,
        descripcion,
        precio,
        estado
    )
    VALUES (
        p_id_categoria,
        p_id_proveedor,
        p_sku,
        p_nombre,
        p_descripcion,
        p_precio,
        p_estado
    );
END;
/

CREATE OR REPLACE PROCEDURE sp_listar_productos (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_producto,
               id_categoria,
               id_proveedor,
               sku,
               nombre,
               descripcion,
               precio,
               estado,
               fecha_creacion
        FROM PRODUCTO
        ORDER BY id_producto;
END;
/


CREATE OR REPLACE PROCEDURE sp_actualizar_producto (
    p_id_producto     IN PRODUCTO.ID_PRODUCTO%TYPE,
    p_id_categoria    IN PRODUCTO.ID_CATEGORIA%TYPE,
    p_id_proveedor    IN PRODUCTO.ID_PROVEEDOR%TYPE,
    p_sku             IN PRODUCTO.SKU%TYPE,
    p_nombre          IN PRODUCTO.NOMBRE%TYPE,
    p_descripcion     IN PRODUCTO.DESCRIPCION%TYPE,
    p_precio          IN PRODUCTO.PRECIO%TYPE,
    p_estado          IN PRODUCTO.ESTADO%TYPE
)
AS
BEGIN
    UPDATE PRODUCTO
       SET id_categoria = p_id_categoria,
           id_proveedor = p_id_proveedor,
           sku = p_sku,
           nombre = p_nombre,
           descripcion = p_descripcion,
           precio = p_precio,
           estado = p_estado
     WHERE id_producto = p_id_producto;
END;
/

CREATE OR REPLACE PROCEDURE sp_eliminar_producto (
    p_id_producto IN PRODUCTO.ID_PRODUCTO%TYPE
)
AS
BEGIN
    DELETE FROM PRODUCTO
    WHERE id_producto = p_id_producto;
END;
/


--- PRUEBA 

BEGIN
    sp_insertar_producto(
        1,
        1,
        'TEC-001',
        'Teclado Mecanico',
        'Teclado mecanico RGB',
        25000,
        'ACTIVO'
    );
    COMMIT;
END;
/


-- CURSOR 

VARIABLE rc REFCURSOR;

BEGIN
    sp_listar_productos(:rc);
END;
/

PRINT rc;




-----------------------------------------------------------------------
---- ROL CRUD 
CREATE OR REPLACE PROCEDURE sp_insertar_rol (
    p_nombre IN ROL.NOMBRE%TYPE
)
AS
BEGIN
    INSERT INTO ROL (nombre)
    VALUES (p_nombre);
END;
/


CREATE OR REPLACE PROCEDURE sp_listar_roles (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_rol, nombre
        FROM ROL
        ORDER BY id_rol;
END;
/

CREATE OR REPLACE PROCEDURE sp_listar_roles (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_rol, nombre
        FROM ROL
        ORDER BY id_rol;
END;
/


CREATE OR REPLACE PROCEDURE sp_eliminar_rol (
    p_id_rol IN ROL.ID_ROL%TYPE
)
AS
BEGIN
    DELETE FROM ROL
    WHERE id_rol = p_id_rol;
END;
/










-----------------------------------------------
---- USUARIO CRUD 

CREATE OR REPLACE PROCEDURE sp_insertar_usuario (
    p_id_rol         IN USUARIO.ID_ROL%TYPE,
    p_nombre         IN USUARIO.NOMBRE%TYPE,
    p_email          IN USUARIO.EMAIL%TYPE,
    p_password_hash  IN USUARIO.PASSWORD_HASH%TYPE,
    p_estado         IN USUARIO.ESTADO%TYPE
)
AS
BEGIN
    INSERT INTO USUARIO (
        id_rol,
        nombre,
        email,
        password_hash,
        estado
    )
    VALUES (
        p_id_rol,
        p_nombre,
        p_email,
        p_password_hash,
        p_estado
    );
END;
/


CREATE OR REPLACE PROCEDURE sp_insertar_usuario (
    p_id_rol         IN USUARIO.ID_ROL%TYPE,
    p_nombre         IN USUARIO.NOMBRE%TYPE,
    p_email          IN USUARIO.EMAIL%TYPE,
    p_password_hash  IN USUARIO.PASSWORD_HASH%TYPE,
    p_estado         IN USUARIO.ESTADO%TYPE
)
AS
BEGIN
    INSERT INTO USUARIO (
        id_rol,
        nombre,
        email,
        password_hash,
        estado
    )
    VALUES (
        p_id_rol,
        p_nombre,
        p_email,
        p_password_hash,
        p_estado
    );
END;
/


CREATE OR REPLACE PROCEDURE sp_actualizar_usuario (
    p_id_usuario     IN USUARIO.ID_USUARIO%TYPE,
    p_id_rol         IN USUARIO.ID_ROL%TYPE,
    p_nombre         IN USUARIO.NOMBRE%TYPE,
    p_email          IN USUARIO.EMAIL%TYPE,
    p_password_hash  IN USUARIO.PASSWORD_HASH%TYPE,
    p_estado         IN USUARIO.ESTADO%TYPE
)
AS
BEGIN
    UPDATE USUARIO
       SET id_rol = p_id_rol,
           nombre = p_nombre,
           email = p_email,
           password_hash = p_password_hash,
           estado = p_estado
     WHERE id_usuario = p_id_usuario;
END;
/

CREATE OR REPLACE PROCEDURE sp_eliminar_usuario (
    p_id_usuario IN USUARIO.ID_USUARIO%TYPE
)
AS
BEGIN
    DELETE FROM USUARIO
    WHERE id_usuario = p_id_usuario;
END;
/





----------------------------------------------------------------
--- INVENTARIO 

CREATE OR REPLACE PROCEDURE sp_insertar_inventario (
    p_id_producto    IN INVENTARIO.ID_PRODUCTO%TYPE,
    p_stock_actual   IN INVENTARIO.STOCK_ACTUAL%TYPE,
    p_stock_minimo   IN INVENTARIO.STOCK_MINIMO%TYPE,
    p_stock_maximo   IN INVENTARIO.STOCK_MAXIMO%TYPE
)
AS
BEGIN
    INSERT INTO INVENTARIO (
        id_producto,
        stock_actual,
        stock_minimo,
        stock_maximo
    )
    VALUES (
        p_id_producto,
        p_stock_actual,
        p_stock_minimo,
        p_stock_maximo
    );
END;
/



CREATE OR REPLACE PROCEDURE sp_listar_inventario (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_inventario,
               id_producto,
               stock_actual,
               stock_minimo,
               stock_maximo
        FROM INVENTARIO
        ORDER BY id_inventario;
END;
/


CREATE OR REPLACE PROCEDURE sp_actualizar_inventario (
    p_id_inventario  IN INVENTARIO.ID_INVENTARIO%TYPE,
    p_stock_actual   IN INVENTARIO.STOCK_ACTUAL%TYPE,
    p_stock_minimo   IN INVENTARIO.STOCK_MINIMO%TYPE,
    p_stock_maximo   IN INVENTARIO.STOCK_MAXIMO%TYPE
)
AS
BEGIN
    UPDATE INVENTARIO
       SET stock_actual = p_stock_actual,
           stock_minimo = p_stock_minimo,
           stock_maximo = p_stock_maximo
     WHERE id_inventario = p_id_inventario;
END;
/



CREATE OR REPLACE PROCEDURE sp_eliminar_inventario (
    p_id_inventario IN INVENTARIO.ID_INVENTARIO%TYPE
)
AS
BEGIN
    DELETE FROM INVENTARIO
    WHERE id_inventario = p_id_inventario;
END;
/






----------------------------------------------------
---- MOVIMIENTO CRUD 

CREATE OR REPLACE PROCEDURE sp_insertar_movimiento (
    p_id_usuario   IN MOVIMIENTO.ID_USUARIO%TYPE,
    p_tipo         IN MOVIMIENTO.TIPO%TYPE,
    p_observacion  IN MOVIMIENTO.OBSERVACION%TYPE
)
AS
BEGIN
    INSERT INTO MOVIMIENTO (
        id_usuario,
        tipo,
        observacion
    )
    VALUES (
        p_id_usuario,
        p_tipo,
        p_observacion
    );
END;
/

CREATE OR REPLACE PROCEDURE sp_listar_movimientos (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_movimiento,
               id_usuario,
               tipo,
               fecha,
               observacion
        FROM MOVIMIENTO
        ORDER BY id_movimiento;
END;
/

CREATE OR REPLACE PROCEDURE sp_actualizar_movimiento (
    p_id_movimiento IN MOVIMIENTO.ID_MOVIMIENTO%TYPE,
    p_id_usuario    IN MOVIMIENTO.ID_USUARIO%TYPE,
    p_tipo          IN MOVIMIENTO.TIPO%TYPE,
    p_observacion   IN MOVIMIENTO.OBSERVACION%TYPE
)
AS
BEGIN
    UPDATE MOVIMIENTO
       SET id_usuario = p_id_usuario,
           tipo = p_tipo,
           observacion = p_observacion
     WHERE id_movimiento = p_id_movimiento;
END;
/

CREATE OR REPLACE PROCEDURE sp_eliminar_movimiento (
    p_id_movimiento IN MOVIMIENTO.ID_MOVIMIENTO%TYPE
)
AS
BEGIN
    DELETE FROM MOVIMIENTO
    WHERE id_movimiento = p_id_movimiento;
END;
/



--------------------------------------
--MOVIMIENTO DETALLE CRUD 

CREATE OR REPLACE PROCEDURE sp_insertar_movimiento_detalle (
    p_id_movimiento   IN MOVIMIENTO_DETALLE.ID_MOVIMIENTO%TYPE,
    p_id_producto     IN MOVIMIENTO_DETALLE.ID_PRODUCTO%TYPE,
    p_cantidad        IN MOVIMIENTO_DETALLE.CANTIDAD%TYPE,
    p_costo_unitario  IN MOVIMIENTO_DETALLE.COSTO_UNITARIO%TYPE
)
AS
BEGIN
    INSERT INTO MOVIMIENTO_DETALLE (
        id_movimiento,
        id_producto,
        cantidad,
        costo_unitario
    )
    VALUES (
        p_id_movimiento,
        p_id_producto,
        p_cantidad,
        p_costo_unitario
    );
END;
/


CREATE OR REPLACE PROCEDURE sp_listar_movimiento_detalle (
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
        SELECT id_detalle,
               id_movimiento,
               id_producto,
               cantidad,
               costo_unitario
        FROM MOVIMIENTO_DETALLE
        ORDER BY id_detalle;
END;
/

CREATE OR REPLACE PROCEDURE sp_actualizar_movimiento_detalle (
    p_id_detalle       IN MOVIMIENTO_DETALLE.ID_DETALLE%TYPE,
    p_id_movimiento    IN MOVIMIENTO_DETALLE.ID_MOVIMIENTO%TYPE,
    p_id_producto      IN MOVIMIENTO_DETALLE.ID_PRODUCTO%TYPE,
    p_cantidad         IN MOVIMIENTO_DETALLE.CANTIDAD%TYPE,
    p_costo_unitario   IN MOVIMIENTO_DETALLE.COSTO_UNITARIO%TYPE
)
AS
BEGIN
    UPDATE MOVIMIENTO_DETALLE
       SET id_movimiento = p_id_movimiento,
           id_producto = p_id_producto,
           cantidad = p_cantidad,
           costo_unitario = p_costo_unitario
     WHERE id_detalle = p_id_detalle;
END;
/



CREATE OR REPLACE PROCEDURE sp_eliminar_movimiento_detalle (
    p_id_detalle IN MOVIMIENTO_DETALLE.ID_DETALLE%TYPE
)
AS
BEGIN
    DELETE FROM MOVIMIENTO_DETALLE
    WHERE id_detalle = p_id_detalle;
END;
/
